/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathLessLayoutRouteImport } from './routes/_pathLessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathLessLayoutManageRouteImport } from './routes/_pathLessLayout.manage'
import { Route as PathLessLayoutDashboardRouteImport } from './routes/_pathLessLayout.dashboard'

const PathLessLayoutRoute = PathLessLayoutRouteImport.update({
  id: '/_pathLessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathLessLayoutManageRoute = PathLessLayoutManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PathLessLayoutRoute,
} as any)
const PathLessLayoutDashboardRoute = PathLessLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PathLessLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof PathLessLayoutDashboardRoute
  '/manage': typeof PathLessLayoutManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof PathLessLayoutDashboardRoute
  '/manage': typeof PathLessLayoutManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathLessLayout': typeof PathLessLayoutRouteWithChildren
  '/_pathLessLayout/dashboard': typeof PathLessLayoutDashboardRoute
  '/_pathLessLayout/manage': typeof PathLessLayoutManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/manage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/manage'
  id:
    | '__root__'
    | '/'
    | '/_pathLessLayout'
    | '/_pathLessLayout/dashboard'
    | '/_pathLessLayout/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathLessLayoutRoute: typeof PathLessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathLessLayout': {
      id: '/_pathLessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathLessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathLessLayout/manage': {
      id: '/_pathLessLayout/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof PathLessLayoutManageRouteImport
      parentRoute: typeof PathLessLayoutRoute
    }
    '/_pathLessLayout/dashboard': {
      id: '/_pathLessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathLessLayoutDashboardRouteImport
      parentRoute: typeof PathLessLayoutRoute
    }
  }
}

interface PathLessLayoutRouteChildren {
  PathLessLayoutDashboardRoute: typeof PathLessLayoutDashboardRoute
  PathLessLayoutManageRoute: typeof PathLessLayoutManageRoute
}

const PathLessLayoutRouteChildren: PathLessLayoutRouteChildren = {
  PathLessLayoutDashboardRoute: PathLessLayoutDashboardRoute,
  PathLessLayoutManageRoute: PathLessLayoutManageRoute,
}

const PathLessLayoutRouteWithChildren = PathLessLayoutRoute._addFileChildren(
  PathLessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathLessLayoutRoute: PathLessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
